### ISSUE TITLE
Work through Freeze checklist

### ISSUE THREAD

**Issue by kd-ods** [openownership/data-standard#629]
From the [release guidance](https://github.com/openownership/bods-dev-handbook/blob/main/standard_releases.md#release-processes):

- [x] Ensure that all pages in the docs/about/ directory have been reviewed and updated if necessary.
- [x] Update the license file (root of repo).
- [x] Update the ReadMe file (root of repo).
- [x] Check docs/schema/reference.rst. Are all new objects, properties and codelists there? Have sub-properties been collapsed sensibly?
- [x] Update BODS version ‘attention’ box on all relevant docs pages
- [x] Do a final edit of docs/schema/changelog.rst
- [x] Fix any sphinx build warnings or errors (including broken links)
- [x] Update all example and test BODS json data to increment bodsVersion value. (And 'bodsVersionTypo' in one test file.) (#685)
- [x] Update the version field value in all schema .json files
- [x] Update the version in index.rst (home page of the docs).
- [x] Update docs/conf.py and check the docs build without errors. (#677)
- [x] Run pytest finally, and resolve any errors.

**Comment by kd-ods** [comment]
@StephenAbbott - the readme in the repo looks ok to me. Is there anything that you want to update in it?

**Comment by StephenAbbott** [comment]
@kd-ods Can you change "beneficial ownership and control of companies" to "beneficial ownership and control of corporate vehicles"? Other than that, looks great 👌

**Comment by kd-ods** [comment]
@StephenAbbott @radix0000 @rhiaro - that's the freeze checklist complete! @odscrachel  and I just finalised it on a call.

@radix0000 - let us know when you've run a final dependency update. At that point we are freezing main :-)

The main branch is built on ReadTheDocs here: https://standard.openownership.org/en/main/index.html. And will remain so while the translation is taking place over the next weeks.

(And for the future, I will be adding that final dependency update to our freeze checklist in the handbook.)

**Comment by StephenAbbott** [comment]
Fantastic. Congratulations @kd-ods @kathryn-ods @odscrachel @rhiaro @radix0000 🎉 🎉 🎉 👏 👏 👏

**Comment by kd-ods** [comment]
Final dependency updates done in PR #697. Closing.
